### ISSUE TITLE
Refactoring for Fastf1 3.X

### ISSUE THREAD

**Issue by Casper-Guo** [Casper-Guo/F1-Data-Visualization#7]
Todos:

- [x] Accommodate newly added columns (position etc.) (#14)
- [x] Remove custom function that adds the position column (#14)
- [x] All old data reprocessed. (#15)
- [x] Depend on `SessionResults` for driver ordering (#13)
- [x] Depend on the new UTC timestamp for determining whether to request new races (#12)
- [x] Standardize docstrings to use Google style (#10)
- [x] Set up proper logging (#11)
- [x] Move all cached data to FastF1 default cache (environment variable changed)
- [x] Revert latest commit according to the [change](https://github.com/theOehrly/Fast-F1/discussions/386#discussioncomment-6065261) on Monaco round number
- [x] Make all `drivers` arguments in plotting functions accept both three-letter abbreviations and driver numbers (#13)
- [x] Remove all cached car_data and position_data
- [x] Rewrite `README.md`, add pictures and update data definitions (#16)
